QLThuVien/Controllers/ThongTinCaNhanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using QLThuVien.Models;

namespace QLThuVien.Controllers
{
   
    public class ThongTinCaNhanController : Controller
    {
        QuanLyThuVienEntities data = new QuanLyThuVienEntities();
        // GET: ThongTinCaNhan
        public ActionResult Index()
        {
            if (Session["DocGia"] == null) return RedirectToAction("Index", "Login");
            return View((DocGia)Session["DocGia"]);
        }

        [HttpPost]
        public ActionResult ChangePassword(FormCollection form)
        {
            DocGia docgia = new DocGia();
            string oldpassword = form["Old password"];
            string newpassword = form["New password"];
            string confirmpassword = form["Confirm password"];
            docgia = (DocGia)Session["DocGia"];
            if (docgia.Password != oldpassword)
            {                
                return Content("<script language='javascript' type='text/javascript'>alert     ('Thất bại! Bạn đã nhập sai mật khẩu cũ');</script>");
            }
            else           
                if (newpassword != confirmpassword)
                {                   
                    return Content("<script language='javascript' type='text/javascript'>alert     ('Thất bại ! Mật khẩu nhập lại không đúng');</script>");
                }
            
            if (docgia.Password == oldpassword && newpassword == confirmpassword)
            {
                docgia.Password = newpassword;
                data.SaveChanges();
                return Content("<script language='javascript' type='text/javascript'>alert     ('Thành công ! Chúc mừng bạn đã đổi mật khẩu thành công');</script>");
            }

            return Content("<script language='javascript' type='text/javascript'>alert     ('Thất bại ! Có thể bạn đã nhập sai thông tin');</script>");
        
    }
    }
}

QLThuVien/Views/ThongTinCaNhan/Index.cshtml
@model QLThuVien.Models.DocGia
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}




<section class="contact spad">
    <div class="container">
        <div class="row">
           
            <div class="col-lg-7 col-md-7">
                <h2 style="margin-bottom:60px">Thông tin cá nhân</h2>
                <div class="contact__content">
                    <div class="contact__address">

                        <ul>
                            <li>
                                <h6><i class="fa fa-navicon"></i> Tên</h6>
                                <p>@Model.TenDG</p>
                            </li>
                            <li>
                                <h6><i class="fa fa-phone"></i> Số điện thoại</h6>
                                <p>@Model.DienThoai</p>
                            </li>
                            <li>
                                <h6><i class="fa fa-map-marker"></i> DiaChi</h6>
                                <p>@Model.DiaChi</p>
                            </li>
                        </ul>
                    </div>

                    @using (Html.BeginForm("ChangePassword", "ThongTinCaNhan", FormMethod.Post, new { enctype = "multipart/formdata" }))
                    {
                        @Html.AntiForgeryToken()
                        <div class="contact__form">
                            <h5>Thay đổi mật khẩu</h5>

                            <input type="password" placeholder="Old password" id="Old password" name="Old password">
                            <td>@Html.ValidationMessageFor(model => model.Password)</td>
                            <input type="password" placeholder="New passwrod" id="New passwrod" name="New password">
                            <td>@Html.ValidationMessageFor(model => model.Password)</td>
                            <input type="password" placeholder="Confirm password" id="Confirm password" name="Confirm password">
                            <button type="submit" value="ChangePassword" class="site-btn">Change password</button>

                        </div>
                    }



                </div>
            </div>
        </div>
    </div>
</section>


<style>
    input {
        width:500px;
        height:50px;
        margin-bottom: 30px;
    }
</style>