QLThuVien/Models/GioSach.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace QLThuVien.Models
{
    public class CartItem
    {
        public Sach giosach { get; set; }   
        public int _soluongSach { get; set; }
    }
    public class GioSach
    {
        List<CartItem> item = new List<CartItem> ();

        public IEnumerable<CartItem> Item
        {
            get { return item; }
        }

        public void Add(Sach _sach, int _quatity = 1)
        {
            var i = item.FirstOrDefault(s => s.giosach.IDSach == _sach.IDSach);
            if (i == null)
            {
                item.Add(new CartItem
                {
                    giosach = _sach,
                    _soluongSach = _quatity
                });                    
            }
            else
            {
                i._soluongSach += _quatity;
            }
        }

        //update số lượng sách
        public void Update (string id, int _quantity)
        {
            var i = item.Find(s => s.giosach.IDSach.Contains(id.ToString()));
            if(i != null)
            {
                if(item.Find(s => s.giosach.SoLuong > _quantity) != null)                
                    i._soluongSach = _quantity;
                else i._soluongSach = 1;
                if (item.Find(s => s.giosach.SoLuong == 0) != null)
                    i._soluongSach = 0;                
            }
        }

        public double sum()
        {
            var sum = item.Sum(s => s._soluongSach * 1);
            return sum;
        }

        public void Remove(string id)
        {
            item.RemoveAll(s => s.giosach.IDSach == id.ToString());
        }

        public int Total()
        {
            return item.Sum(s => s._soluongSach);
        }

        public void clear()
        {
            item.Clear();
        }

        public void ssss()
        {
            DateTime aDateTime = DateTime.Now;

            Console.WriteLine("Now is " + aDateTime);

            // Một khoảng thời gian. 
            // 1 giờ + 1 phút
            TimeSpan aInterval = new System.TimeSpan(0, 1, 1, 0);

            // Thêm một khoảng thời gian.
            DateTime newTime = aDateTime.Add(aInterval);
        }
    }
}

QLThuVien/Controllers/GioSachController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using QLThuVien.Models;

namespace QLThuVien.Controllers
{
    public class GioSachController : Controller
    {
        QuanLyThuVienEntities data = new QuanLyThuVienEntities();
        // GET: GioSach
        public GioSach GetSach()
        {
            GioSach gio = Session["GioSach"] as GioSach;
            if (gio == null || Session["GioSach"] == null)
            {
                gio = new GioSach();
                Session["GioSach"] = gio;
            }
            return gio;
        }

        // GET: GioSach
        [HttpGet]
        public ActionResult Index()
        {

            if (Session["UserName"] == null)
            {
                return RedirectToAction("Index", "Login");
            }
            return View();
        }

        public ActionResult Addto(string id)
        {
            if (Session["UserName"] == null)
            {
                return RedirectToAction("Index", "Login");
            }
            else
            {
                var gio = data.Saches.SingleOrDefault(s => s.IDSach == id);
                if (gio != null)
                {
                    GetSach().Add(gio);
                }
                return RedirectToAction("Show", "GioSach");
            }
        }

        public ActionResult Show()
        {
            if (Session["UserName"] == null)
            {
                return RedirectToAction("Index", "Login");
            }
            if (Session["GioSach"] == null)
            {
                return RedirectToAction("Show", "GioSach");
            }
        
            DocGia dg = Session["DocGia"] as DocGia;

            if (dg != null)
            {
                ViewBag.IDDG = dg.IDDG;
                ViewBag.TenDG = dg.TenDG;
            }

            GioSach gio = Session["GioSach"] as GioSach;
            return View(gio);
        }


        //FormCollection is one way of retrieving view data in controller.
        //Depending on the type of value in input,
        //you can parse its non-string value to string in the Action method.
        public ActionResult Update_quantity(FormCollection form)
        {
            GioSach gio = Session["GioSach"] as GioSach;
            string id_sach = form["Id sach"];
            int quantity = int.Parse(form["quantity"]);
            gio.Update(id_sach, quantity);
            return RedirectToAction("Show", "GioSach");
        }

        public ActionResult Remove(string id)
        {
            GioSach gio = Session["GioSach"] as GioSach;
            gio.Remove(id);
            return RedirectToAction("Show", "GioSach");
        }


        //PartialViewResult is used to return the partial view.
        //Basically, it is a class which implements the ViewResultBase abstract class that used to render partial view.
        //PartialViewResult class inherit from ViewResultBase class
        public PartialViewResult BagBook()
        {
            int total = 0;
            GioSach gio = Session["GioSach"] as GioSach;
            if (gio != null)
            {
                total = gio.Total();
            }

            ViewBag.infocart = total;
            return PartialView("BagBook");
        }

        public ActionResult Muon_Success()
        {
            return View();
        }

        [HttpPost]
        public ActionResult MuonSach(FormCollection form)
        {
            try
            {
                GioSach gio = Session["GioSach"] as GioSach;
                DocGia docgia = Session["DocGia"] as DocGia;
                PhieuMuon muon = new PhieuMuon();
                muon.IDDG = docgia.IDDG;
                muon.TenDG = docgia.TenDG;
                muon.NgayMuon = DateTime.Now;
                muon.TienPhat = 0;
                muon.GhiChu = "";
                muon.TrangThai = 1;
                muon.NgayTra = DateTime.Parse(form["NgayTra"]);

                DateTime ngaymuon = Convert.ToDateTime(muon.NgayMuon);
                DateTime ngaytra = Convert.ToDateTime(muon.NgayTra);

                TimeSpan Time = ngaytra - ngaymuon;
                int TongSoNgay = Time.Days;

                if (TongSoNgay > 15)
                {
                    //return Content("Lỗi ! Thời gian mượn tối đa là 15 ngày");
                    return Content("<script language='javascript' type='text/javascript'>alert     ('Lỗi ! Thời gian mượn tối đa là 15 ngày');</script>");
                }


                // check status phieumuon is return
                List<PhieuMuon> listphieuMuon = data.PhieuMuons.Where(c => c.IDDG == muon.IDDG).ToList();
                foreach (PhieuMuon item in listphieuMuon)
                {
                    if (item.TrangThai == 2 || item.TrangThai == 1)
                    {
                        //return Content("Lỗi ! Chưa trả sách mượn lần trước");
                        return Content("<script language='javascript' type='text/javascript'>alert     ('Lỗi ! Bạn chưa trả sách đã mượn nên không được mượn');</script>");
                    }
                }

                foreach (var pm in data.PhieuMuons.Where(s => s.IDDG == muon.IDDG))
                {
                    if (pm.TienPhat != 0)
                    {
                        //return Content("Độc giả chưa đóng tiền phạt thì không được mượn thêm sách!");
                        return Content("<script language='javascript' type='text/javascript'>alert     ('Độc giả chưa đóng tiền phạt thì không được mượn thêm sách!');</script>");
                    }
                }

                if (TongSoNgay <= 0)
                {
                    //return Content("Lỗi ! Vui lòng kiểm tra lại mốc thời gian");
                    return Content("<script language='javascript' type='text/javascript'>alert     ('Lỗi ! Vui lòng kiểm tra lại mốc thời gian');</script>");
                }

                int total = gio.Total();
                if (total > 3)
                {
                    return Content("<script language='javascript' type='text/javascript'>alert     ('Tối đa được mượn 3 quyển sách');</script>");
                    //return Content("Tối đa được mượn 3 loại sách");
                }

                //Add phiếu mượn
                data.PhieuMuons.Add(muon);
               


                foreach (var item in gio.Item)
                {
                    int tongsach = 0;
                    tongsach = tongsach + 1;


                    if (item._soluongSach == 0)
                    {
                        return Content("<script language='javascript' type='text/javascript'>alert     ('Vui lòng kiểm tra số lượng! Do có sách không còn đủ số lượng');</script>");
                        //return Content("Vui lòng kiểm tra số lượng! Do có sách không còn đủ số lượng");

                    }
                    if (tongsach == 0)
                    {
                        return Content("<script language='javascript' type='text/javascript'>alert     ('Không có sách thì không thể tạo phiếu mượn!');</script>");
                    }

                    CT_PM Detail = new CT_PM();
                    Detail.IDPM = muon.IDPM;
                    Detail.IDSach = item.giosach.IDSach;
                    Detail.SoLuong = item._soluongSach;


                    // update số lượng sách
                    foreach (var p in data.Saches.Where(s => s.IDSach == Detail.IDSach))
                    {
                        var update_soluong = p.SoLuong - item._soluongSach;
                        p.SoLuong = update_soluong;
                    }

                    foreach (var p in data.Saches.Where(s => s.IDSach == Detail.IDSach))
                    {
                        if (p.SoLuong < item._soluongSach)
                        {
                            /* return Content("Không đủ sách theo yêu cầu của Độc Giả!");*/
                            return Content("<script language='javascript' type='text/javascript'>alert     ('Không đủ sách theo yêu cầu của Độc Giả!');</script>");
                        }
                    }


                    //Add chi tiết phiếu mượn
                    data.CT_PM.Add(Detail);
                  
                }
                data.SaveChanges();
                gio.clear();
                return RedirectToAction("Muon_Success", "GioSach");
            }
            catch
            {
                return Content("Vui lòng kiểm tra lại thông tin!");
            }
        }
    }
}

QLThuVien/Controllers/SachController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using QLThuVien.Models;
using PagedList;

namespace QLThuVien.Controllers
{
    public class SachController : Controller
    {
        QuanLyThuVienEntities data = new QuanLyThuVienEntities();
        // GET: Sach
        public ActionResult Index(string theloai, string tensach, int page = 1, int pagelist = 6)
        {
            ViewBag.TheLoai = data.TheLoais.ToList();            

            if (theloai != null)
            {
                return View(data.Saches.Where(c => c.TheLoai1.NameCate.ToLower().Contains(theloai.ToLower())).OrderByDescending(c => c.NgayXuatBan).ToPagedList(page,pagelist));
            }
            if (tensach != null)
            {
                
                return View(data.Saches.Where(c => c.TenSach.ToLower().Contains(tensach.ToLower())).OrderByDescending(c => c.NgayXuatBan).ToPagedList(page, pagelist));
            }
            return View(data.Saches.OrderByDescending(c => c.NgayXuatBan).ToPagedList(page, pagelist));
        }
    }
}

QLThuVien/Views/GioSach/BagBook.cshtml
@model QLThuVien.Models.GioSach 
@{
    ViewBag.Title = "BagBook";
}

<h2>Số lượng sách đã mượn</h2>

<span style="color:red;margin-left:5px">@ViewBag.infocart</span>

QLThuVien/Views/GioSach/Muon_Success.cshtml
@{
    ViewBag.Title = "Muon_Success";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="dfdf">
    <h3>BẠN ĐÃ MƯỢN SÁCH THÀNH CÔNG</h3>
    <a href="@Url.Action("Index","Sach")" class="btn btn-primary">Trở Về</a>
</div>

<style>
    .dfdf {
       margin-top:200px;
       margin-bottom:200px;
        top: 30%;
        left: 30%;
        text-align: center
    }
</style>

QLThuVien/Views/GioSach/Show.cshtml
@model QLThuVien.Models.GioSach
@{
    ViewBag.Title = "Show";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 style="text-align:center; color:royalblue">Phiếu Mượn Sách</h2>


@if (Model != null)
{

    <div class="container">

        <table class="table">
            <thead>
                <tr>
                    <th>Tên Sách</th>
                    <th>Tác giả</th>
                    <th>Hình ảnh</th>
                    <th>Thể Loại</th>
                    <th>Số Lượng</th>
                    <th>Tổng cộng</th>
                    <th>Xóa</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Item)
                {
                    double sum = item._soluongSach * 1;
                    <tr>
                        <td>@Html.DisplayFor(Model => item.giosach.TenSach)</td>
                        <td>@Html.DisplayFor(Model => item.giosach.TacGia)</td>
                        <td>
                            @{
                                var base64 = Convert.ToBase64String(item.giosach.HinhAnh);
                                var imgSrc = String.Format("data:image/gif;base64,{0}", base64);
                            }
                            <img src='@imgSrc' style="width:150px;height:150px" />
                        </td>
                       
                        <td>@Html.DisplayFor(Model => item.giosach.TheLoai1.NameCate)</td>
                        <td>
                            @using (Html.BeginForm("Update_quantity", "GioSach"))
                            {
                                <input type="hidden" value="@item.giosach.IDSach" name="Id sach" />
                                <input type="number" value="@item._soluongSach" name="quantity" />
                                <input type="submit" value="Update" />
                            }
                        </td>
                        <td>ToTal: @sum</td>
                        <td><a href="/GioSach/Remove/@item.giosach.IDSach">Xóa</a></td>
                    </tr>
                }
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="2"></td>
                    <td colspan="4" style="text-align:center">
                        @using (Html.BeginForm("MuonSach", "GioSach", FormMethod.Post, new { enctype = "multipart/formdata" }))
                        {
                            <table style="border-collapse:separate;border-spacing:5px">

                                <tr>
                                    <td>ID độc giả:</td>
                                    <td> <input type="text" name="IDdocgia" value="@ViewBag.IDDG" /></td>
                                </tr>
                                <tr>
                                    <td>Tên độc giả:</td>
                                    <td><input type="text" name="Tendg" value="@ViewBag.TenDG" /></td>
                                    <td></td>
                                </tr>
                                <tr>
                                    <td>Ngày Mượn:</td>
                                    <td><input type="datetime" value="@DateTime.Now" /></td>
                                    <td></td>
                                </tr>
                                <tr>
                                    <td>Ngày Trả:</td>
                                    <td><input type="datetime-local" name="NgayTra" /></td>
                                    <td></td>
                                </tr>

                                <tr>
                                    <td></td>

                                    <td>
                                        <input class="btn site-btn" type="submit" name="Muon" value="Mượn Sách" />
                                    </td>
                                    <td></td>
                                </tr>
                            </table>
                        }
                    </td>

                </tr>
                <tr>
                    <td colspan="5" style="text-align:right">Tổng Cộng: @Model.sum()</td>
                </tr>
                <div class="product__details__button" style="float:left">
                    <a href="~/Sach/index" class="cart-btn">Tiếp tục mượn sách</a>

                </div>
            </tfoot>
        </table>
    </div>
}