QLThuVien/Areas/Admin/Controllers/AdminSachesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using QLThuVien.Models;

namespace QLThuVien.Areas.Admin.Controllers
{
    public class AdminSachesController : Controller
    {
        private QuanLyThuVienEntities db = new QuanLyThuVienEntities();

        // GET: Admin/AdminSaches
        public ActionResult Index(string tensach)
        {
            if (Session["UserName"] == null)
            {
                return RedirectToAction("Index", "AdminLogin", new { Areas = "Admin" });
            }
            else
            {
                if(tensach == null)
                {                    
                    return View(db.Saches.ToList());
                }
                else if (tensach.Equals(""))
                {
                    return View(db.Saches.ToList());
                }
                else
                {                    
                    return View(db.Saches.Where(s => s.TenSach.ToLower().Contains(tensach.ToLower())).ToList());
                }
               
            }           
        }

        // GET: Admin/AdminSaches/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sach sach = db.Saches.Find(id);
            if (sach == null)
            {
                return HttpNotFound();
            }
            return View(sach);
        }

        // GET: Admin/AdminSaches/Create
        public ActionResult Create()
        {  
            List<TheLoai> list = db.TheLoais.ToList();          
            ViewBag.TheLoai = new SelectList(db.TheLoais, "IDCate", "NameCate");
            Sach sach = new Sach();
            return View(sach);
        }

        // POST: Admin/AdminSaches/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.

        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult Create(Sach sach)
        {
            try
            {
                List<TheLoai> list = db.TheLoais.ToList();
                if (sach.UploadImage != null)
                {
                    using (var binaryReader = new BinaryReader(sach.UploadImage.InputStream))
                        sach.HinhAnh = binaryReader.ReadBytes(sach.UploadImage.ContentLength);
                }
                ViewBag.TheLoai = new SelectList(db.TheLoais, "IDCate", "NameCate", sach.TheLoai);
                db.Saches.Add(sach);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return Content("<script language='javascript' type='text/javascript'>alert ('Vui lòng kiểm tra lại thông tin!');</script>");
            }
        }

     

        // GET: Admin/AdminSaches/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sach sach = db.Saches.Find(id);
            Session["HinhAnh"] = sach.HinhAnh;
            if (sach == null)
            {
                return HttpNotFound();
            }
            ViewBag.TheLoai = new SelectList(db.TheLoais, "IDCate", "NameCate", sach.TheLoai);
            return View(sach);
        }

        
        // POST: Admin/AdminSaches/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Sach sach)
        {
            
            if(sach.UploadImage != null)
            {
                using (var binaryReader = new BinaryReader(sach.UploadImage.InputStream))
                    sach.HinhAnh = binaryReader.ReadBytes(sach.UploadImage.ContentLength);
            }
            else
            {
                if (Session["HinhAnh"] != null)
                {
                    sach.HinhAnh = (byte[])Session["HinhAnh"];
                    Session.Remove("HinhAnh");
                }
                
                else return RedirectToAction("Index");

            }
            if (ModelState.IsValid)
            {
                
                db.Entry(sach).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.TheLoai = new SelectList(db.TheLoais, "IDCate", "IDCate", sach.TheLoai);
            return View(sach);
        }

        // GET: Admin/AdminSaches/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sach sach = db.Saches.Find(id);
            if (sach == null)
            {
                return HttpNotFound();
            }
            return View(sach);
        }

        // POST: Admin/AdminSaches/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            try
            {
                Sach sach = db.Saches.Find(id);
                db.Saches.Remove(sach);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return Content("<script language='javascript' type='text/javascript'>alert     ('Cuốn sách này đang đươc mượn!');</script>");
            }
    
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

QLThuVien/Areas/Admin/Views/AdminSaches/Create.cshtml
@model QLThuVien.Models.Sach

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

@using (Html.BeginForm("Create", "AdminSaches", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="col-md-6 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Tạo một cuốn sách mới</h4>

                <form class="forms-sample">
                    <div class="form-group row">
                        <label for="exampleInputUsername2" class="col-sm-3 col-form-label">ID cuốn sách</label>
                        <div class="col-sm-9">
                            @Html.EditorFor(model => model.IDSach, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.IDSach, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="exampleInputUsername2" class="col-sm-3 col-form-label">Tên sách</label>
                        <div class="col-sm-9">
                            @Html.EditorFor(model => model.TenSach, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.TenSach, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="exampleInputEmail2" class="col-sm-3 col-form-label">Mô tả </label>
                        <div class="col-sm-9">
                            @Html.EditorFor(model => model.MoTa, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.MoTa, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="exampleInputEmail2" class="col-sm-3 col-form-label">Tác giả</label>
                        <div class="col-sm-9">
                            @Html.EditorFor(model => model.TacGia, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.TacGia, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="exampleInputEmail2" class="col-sm-3 col-form-label">Ngày xuất bản</label>
                        <div class="col-sm-9">
                            @Html.EditorFor(model => model.NgayXuatBan, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.NgayXuatBan, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="exampleInputEmail2" class="col-sm-3 col-form-label">Số lượng</label>
                        <div class="col-sm-9">
                            @Html.EditorFor(model => model.SoLuong, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.SoLuong, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="exampleInputEmail2" class="col-sm-3 col-form-label">Thể loại</label>
                        <div class="col-sm-9">
                            @Html.DropDownList("TheLoai", null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.TheLoai, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="exampleInputEmail2" class="col-sm-3 col-form-label">Hình ảnh</label>
                        <div class="col-sm-9">
                            <input type="file" name="UploadImage" />                            
                            @Html.ValidationMessageFor(model => model.HinhAnh, "", new { @class = "text-danger" })
                        </div>
                    </div>


                    <button style="width:100px; type="submit" value="Create" class="btn btn-primary mr-2">Create</button>

                    <a href="~/Admin/AdminSaches/Index">
                        <button type="button" class="btn btn-outline-secondary btn-lg btn-block" style="width:300px; margin-top:40px">Trở về</button>
                    </a>
                </form>
            </div>
        </div>
    </div>
}

QLThuVien/Areas/Admin/Views/AdminSaches/Delete.cshtml
@model QLThuVien.Models.Sach

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h2>Delete</h2>

<h3>Bạn có muốn xóa cuốn sách này không</h3>

<div class="col-md-6 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Chi tiết của cuốn sách</h4>

            <form class="forms-sample">
                <div class="form-group row">
                    <label for="exampleInputUsername2" class="col-sm-3 col-form-label">Tên sách</label>
                    <div class="col-sm-9">
                        @Html.DisplayFor(model => model.TenSach)
                    </div>
                </div>
                <div class="form-group row">
                    <label for="exampleInputEmail2" class="col-sm-3 col-form-label">Mô tả </label>
                    <div class="col-sm-9">
                        @Html.DisplayFor(model => model.MoTa)
                    </div>
                </div>
                <div class="form-group row">
                    <label for="exampleInputEmail2" class="col-sm-3 col-form-label">Tác giả</label>
                    <div class="col-sm-9">
                        @Html.DisplayFor(model => model.TacGia)
                    </div>
                </div>
                <div class="form-group row">
                    <label for="exampleInputEmail2" class="col-sm-3 col-form-label">Ngày xuất bản</label>
                    <div class="col-sm-9">
                        @Html.DisplayFor(model => model.NgayXuatBan)
                    </div>
                </div>
                <div class="form-group row">
                    <label for="exampleInputEmail2" class="col-sm-3 col-form-label">Số lượng</label>
                    <div class="col-sm-9">
                        @Html.DisplayFor(model => model.SoLuong)
                    </div>
                </div>
                <div class="form-group row">
                    <label for="exampleInputEmail2" class="col-sm-3 col-form-label">Hình ảnh</label>
                    <div class="col-sm-9">
                        @* <img src="@Url.Content(Model.HinhAnh)" style="width: 100px; height: 150px; border-radius:0%" />*@
                        @{
                            var base64 = Convert.ToBase64String(Model.HinhAnh);
                            var imgSrc = String.Format("data:image/gif;base64,{0}", base64);
                        }
                        <img src='@imgSrc' style="width: 100px; height: 150px; border-radius:0%" />
                    </div>
                </div>
                <div class="form-group row">
                    <label for="exampleInputEmail2" class="col-sm-3 col-form-label">Thể loại</label>
                    <div class="col-sm-9">
                        @Html.DisplayFor(model => model.TheLoai1.NameCate)
                    </div>
                </div>

                

            </form>
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-actions no-color">        
                    <button style="width:180px; type="submit" value="Delete"class="btn btn-primary mr-2">Delete</button>
                </div>
            }
            <a href="~/Admin/AdminSaches/Index">
                <button type="button" class="btn btn-outline-secondary btn-lg btn-block" style="width:300px; margin-top:40px">Trở về</button>
            </a>
        </div>
    </div>
</div>

QLThuVien/Areas/Admin/Views/AdminSaches/Details.cshtml
@model QLThuVien.Models.Sach

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}



<div class="col-md-6 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Chi tiết của cuốn sách</h4>

            <form class="forms-sample">
                <div class="form-group row">
                    <label for="exampleInputUsername2" class="col-sm-3 col-form-label">Tên sách</label>
                    <div class="col-sm-9">
                        @Html.DisplayFor(model => model.TenSach)
                    </div>
                </div>
                <div class="form-group row">
                    <label for="exampleInputEmail2" class="col-sm-3 col-form-label">Mô tả </label>
                    <div class="col-sm-9">
                        @Html.DisplayFor(model => model.MoTa)
                    </div>
                </div>
                <div class="form-group row">
                    <label for="exampleInputEmail2" class="col-sm-3 col-form-label">Tác giả</label>
                    <div class="col-sm-9">
                        @Html.DisplayFor(model => model.TacGia)
                    </div>
                </div>
                <div class="form-group row">
                    <label for="exampleInputEmail2" class="col-sm-3 col-form-label">Ngày xuất bản</label>
                    <div class="col-sm-9">
                        @Html.DisplayFor(model => model.NgayXuatBan)
                    </div>
                </div>
                <div class="form-group row">
                    <label for="exampleInputEmail2" class="col-sm-3 col-form-label">Số lượng</label>
                    <div class="col-sm-9">
                        @Html.DisplayFor(model => model.SoLuong)
                    </div>
                </div>
                <div class="form-group row">
                    <label for="exampleInputEmail2" class="col-sm-3 col-form-label">Hình ảnh</label>
                    <div class="col-sm-9">                      
                        @{
                            var base64 = Convert.ToBase64String(Model.HinhAnh);
                            var imgSrc = String.Format("data:image/gif;base64,{0}", base64);
                        }
                        <img src='@imgSrc' style="width: 100px; height: 150px; border-radius:0%" />
                    </div>
                    
                        
                    
                </div>
                <div class="form-group row">
                    <label for="exampleInputEmail2" class="col-sm-3 col-form-label">Thể loại</label>
                    <div class="col-sm-9">
                        @Html.DisplayFor(model => model.TheLoai1.NameCate)
                    </div>
                </div>

                <a href="~/Admin/AdminSaches/Edit/@Model.IDSach">
                    <button style="width:100px; type="button" class="btn btn-primary mr-2">Edit</button>
                </a>

                <a href="~/Admin/AdminSaches/Index">
                    <button type="button" class="btn btn-outline-secondary btn-lg btn-block" style="width:300px; margin-top:40px">Trở về</button>
                </a>


            </form>
        </div>
    </div>
</div>

QLThuVien/Areas/Admin/Views/AdminSaches/Edit.cshtml
@model QLThuVien.Models.Sach

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

@using (Html.BeginForm(Html.BeginForm("Edit", "AdminSaches", FormMethod.Post, new { enctype = "multipart/form-data" })))
{
    @Html.AntiForgeryToken()

    <div class="col-md-6 grid-margin stretch-card">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Bạn muốn chỉnh sửa thông tin cuốn sách</h4>

                <form class="forms-sample">
                    <div class="form-group row">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.IDSach)
                        <label for="exampleInputUsername2" class="col-sm-3 col-form-label">Tên sách</label>

                        <div class="col-sm-9">
                            @Html.EditorFor(model => model.TenSach, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.TenSach, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="exampleInputEmail2" class="col-sm-3 col-form-label">Mô tả </label>
                        <div class="col-sm-9">
                            @Html.EditorFor(model => model.MoTa, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.MoTa, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="exampleInputEmail2" class="col-sm-3 col-form-label">Tác giả</label>
                        <div class="col-sm-9">
                            @Html.EditorFor(model => model.TacGia, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.TacGia, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="exampleInputEmail2" class="col-sm-3 col-form-label">Ngày xuất bản</label>
                        <div class="col-sm-9">
                            @Html.EditorFor(model => model.NgayXuatBan, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.NgayXuatBan, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="exampleInputEmail2" class="col-sm-3 col-form-label">Số lượng</label>
                        <div class="col-sm-9">
                            @Html.EditorFor(model => model.SoLuong, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.SoLuong, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    


                    <div class="form-group row">
                        <label for="exampleInputEmail2" class="col-sm-3 col-form-label">Hình ảnh</label>
                        <td>
                            @{                                
                                var base64 = Convert.ToBase64String(Model.HinhAnh);
                                var imgSrc = String.Format("data:image/gif;base64,{0}", base64);
                            }
                            <img src='@imgSrc' style="width: 100px; height: 150px; border-radius:0%" />
                        </td>

                        <input type="file" name="UploadImage" />
                        @Html.ValidationMessageFor(model => model.HinhAnh, "", new { @class = "text-danger" })

                        @*  <div class="col-sm-9">
            @Html.EditorFor(model => model.HinhAnh, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.HinhAnh, "", new { @class = "text-danger" })
        </div>*@
                    </div>
                    <div class="form-group row">
                        <label for="exampleInputEmail2" class="col-sm-3 col-form-label">Thể loại</label>
                        <div class="col-sm-9">
                            @Html.DropDownList("TheLoai", null, htmlAttributes: new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.TheLoai, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <button style="width:100px; type="submit" value="Save" class="btn btn-primary mr-2">Save</button>

                    <a href="~/Admin/AdminSaches/Index">
                        <button type="button" class="btn btn-outline-secondary btn-lg btn-block" style="width:300px; margin-top:40px">Trở về</button>
                    </a>
                </form>
            </div>
        </div>
    </div>
}

QLThuVien/Areas/Admin/Views/AdminSaches/Index.cshtml
@model IEnumerable<QLThuVien.Models.Sach>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}



<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h2 class="card-title">Danh sách sách trong thư viện</h2>

            <a href="~/Admin/AdminSaches/Create">
                <button type="button" class="btn btn-primary btn-fw">Tạo một cuốn sách mới</button>
            </a>

            <form class="nav-link mt-2 mt-md-0 d-none d-lg-flex search">
                <input type="text" class="form-control" placeholder="Tìm kiếm theo tên sách" name="tensach">
            </form>
            <div class="table-responsive">
                
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th style="color:white">
                                ID Sách
                            </th>
                            <th style="color:white">
                                Tên sách
                            </th>
                            <th style="color:white">
                                Tác giả
                            </th>
                            <th style="color:white">
                                Ngày xuất bản
                            </th>
                            <th style="color:white">
                                Số lượng
                            </th>
                            <th style="color:white">
                                Hình ảnh
                            </th>
                            <th style="color:white">
                                Thể loại
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>

                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.IDSach)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.TenSach)
                                </td>

                                <td>
                                    @Html.DisplayFor(modelItem => item.TacGia)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.NgayXuatBan)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.SoLuong)
                                </td>
                                <td>
                                    @{
                                        var base64 = Convert.ToBase64String(item.HinhAnh);
                                        var imgSrc = String.Format("data:image/gif;base64,{0}", base64);
                                    }
                                    <img src='@imgSrc' style="width: 100px; height: 150px; border-radius:0%" />
                                </td>                           
                                <td>
                                    @Html.DisplayFor(modelItem => item.TheLoai1.NameCate)
                                </td>

                                <td>

                                    <a href="~/Admin/AdminSaches/Details/@item.IDSach">
                                        <button style="min-width:50px" type="button" class="btn btn-outline-success btn-fw">Details</button>
                                    </a>
                                    <a href="~/Admin/AdminSaches/Edit/@item.IDSach">
                                        <button style="min-width:50px" type="button" class="btn btn-outline-warning btn-fw">Edit</button>
                                    </a>
                                    <a href="~/Admin/AdminSaches/Delete/@item.IDSach">
                                        <button style="min-width:50px" type="button" class="btn btn-outline-danger btn-fw">Delete</button>
                                    </a>
                                    <a href="~/Admin/AdminChiTietSaches/Index/?IDSach=@item.IDSach">
                                        <button style="min-width:50px" type="button" class="btn btn-outline-light btn-fw">Chi tiết các cuốn sách</button>
                                    </a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>